name: 'Random name'
# test different workflow triggers
on:
  push:
    branches: [feature/**]

jobs:
  test_sum_function:
    # run job(s) on latest virtual machine hosted by GH
    runs-on: ubuntu-latest

    steps:
      # checks out repo onto runner, allowing scripts usage (build & test)
      - uses: actions/checkout@v3
      - name: Use Node.js
        # installs specified version of Node.js - allows usage of node & npm commands
        uses: actions/setup-node@v3
      - name: Install
        run: npm ci
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Jest Test
        run: npm t

  console_log_auto_test_package_function:
    needs: test_sum_function
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Console log
        run: node src/index.js
