name: 'Random name'
# test different workflow triggers
on:
  push:
    branches: [feature/**]

jobs:
  test_sum_function:
    # run job(s) on latest virtual machine hosted by GH
    runs-on: ubuntu-latest

    steps:
      # THIS DOESN'T WORK
      # checks out repo onto runner, allowing scripts usage (build & test)
      - uses: actions/checkout@v3
      - name: Use Node.js
        # installs specified version of Node.js - allows usage of node & npm commands
        uses: actions/setup-node@v3
        # Okay so if we don't have NPM_TOKEN: ${{ secrets.GH_TOKEN }} (currently using PAT), we get authentication warning.
        # We are downloading a Github Package when we run npm ci, the auto-package-test. So question is: why specifically NPM_TOKEN
      - name: Install
        run: npm ci
        # setting secret as environment variable
        env:
          NPM_TOKEN: ${{ secrets.GH_TOKENN }}
