# name: CI-Github-Actions
name: 'Random name'
# test different workflow triggers
on:
  push:
    branches: [feature/**]

jobs:
  test_sum_function:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
      - name: Jest Test
        run: npm t

  console_log_sum_function_again:
    needs: test_sum_function
    runs-on: ubuntu-latest

    steps: 
      uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
      - name: Console log
        run: node src/sum.js
